### ISSUE TITLE
CocoaAMF-iPhone sample works with amfphp but not ColdFusion remoting

### ISSUE THREAD

**Issue by mgithens** [nesium/cocoa-amf#1]
I have provided the sample code below. Any suggestions would be much appreciated.
## Error Message:

{
    code = "Server.Processing";
    details = <null>;
    message = "No destination with id 'ExampleService' is registered with any service.";
    rootCause = <null>;
}
## DemoCaller.m

m_remotingCall.URL = [NSURL URLWithString:@"http://mydomain.com/flex2gateway"];
m_remotingCall.service = @"ExampleService";
## ExampleService.cfc

<cfcomponent displayname="ExampleService">
    <cffunction name="add" access="remote" returntype="numeric">
        <cfargument name="addende1" type="numeric" required="yes">
        <cfargument name="addende2" type="numeric" required="yes">
        <cfreturn addende1 + addende2>
    </cffunction>

```
<cffunction name="hello" access="remote" returntype="string">
    <cfreturn "hello world!">
</cffunction>

<cffunction name="returnArray" access="remote" returntype="array">
    <cfset var ar = ['1','2','3','apple','pears','oranges'] />
    <cfreturn ar>
</cffunction>

<cffunction name="returnFloat" access="remote" returntype="numeric">
    <cfset var float = 1.23456789 />
    <cfreturn float>
</cffunction>      
```

</cfcomponent>

**Comment by nesium** [comment]
hi. unfortunately i have no clue of coldfusion, but i think the error message looks much like it the problem is on the serverside. have you verfied that your cf code works with a flex app for example?
