### ISSUE TITLE
Calling BlazeDS where RemoteClass/Alias is needed

### ISSUE THREAD

**Issue by vigupta** [nesium/cocoa-amf#3]
Looking through the examples I didn't see a way to make a Remote Call where the RemoteClass needed to be specified.  In the .net AMF calls there is a way to specify the remote class.  Any hints?

Thanks

**Comment by nesium** [comment]
do you mean mapping a cocoa class to a java class?
does the wiki entry help? http://wiki.github.com/nesium/cocoa-amf/custom-type-mappings-custom-classes

**Comment by vigupta** [comment]
I saw that and I think that might be it wasn't sure.  I was thinking of using the following:

[AMFUnarchiver setClass:[MyBook class] forClassName:@"com.mycompany.book"];
[AMFArchiver setClassName:@"com.mycompany.book" forClass:[MyBook class]];

This would then substitute for the following type of call within ActionScript:
[RemoteClass(alias="com.mycompany.book")]

Does that sound right?  So the AMF message being sent with the serialized object would be correctly converted to the right object?

Thanks.

**Comment by nesium** [comment]
that looks perfectly fine and should work. so, tell me if it doesn't.

**Comment by zinnoo88** [comment]
How can I send something like "flex.messaging.messages.RemotingMessage.operation
source.body.clientId.timeToLive.timestamp.headers.destination.messageId.." using cocoa-amf?
