### ISSUE TITLE
Problem with scandinavian characters

### ISSUE THREAD

**Issue by johax** [nesium/cocoa-amf#5]
This is a great library that I am using to make a iPhone version of my flex application. 
I have this problem that I can't figure out how to solve. It's when I try to send anything that contains scandinavian characters (Å Ä Ö for example) the application crashes.
The error I get is like this:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSCFDictionary setObject:forKey:]: attempt to insert nil value (key: mod_name)'

The value for mod_name is 'Timepört' if I change it to 'Timeport' everything is fine. but it looks like the value is nil for some reason.
Also if I utf8_encode() the variable on server-side in my php function it works. But thats nothing I would like to do in all functions I built and loop all arrays and so on. My database is encoded in UTF-8 and Im using the SabreAMF framework.

Thanks!

regard,
Johan Axlesson

**Comment by nesium** [comment]
hi johan. quickly tested this with a amfphp service. and it works perfectly fine for me.

here is the code that i've used on the php side:

<pre><code>$conn = mysql_connect('localhost', 'db', 'pass');
mysql_select_db('table');
$res = mysql_query('SELECT * FROM test');
$rows = array();
while ($row = mysql_fetch_assoc($res)){
    array_push($rows, $row);
}
mysql_free_result($res);
mysql_close($conn);
return $rows;</code></pre>


the table looks like this

<pre><code>CREATE TABLE `test` (
  `id` int(11) NOT NULL auto_increment,
  `mod_name` varchar(255) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

LOCK TABLES `test` WRITE;
/*!40000 ALTER TABLE `test` DISABLE KEYS */;
INSERT INTO `test` (`id`,`mod_name`)
VALUES
    (1,'Timepört'),
    (2,'Ånother entry');

/*!40000 ALTER TABLE `test` ENABLE KEYS */;
UNLOCK TABLES;</code></pre>


so does it work with a flash frontend? and can i test your service anywhere, if so?

cheers,
marc

**Comment by johax** [comment]
thanks for fast answer and testing.
well it seems like the problem is in SabreAMF then I guess.
Yes it works with no problem with a flash frontend.
I have a test server here, might be down at some times: http://home.studio.ax/OnePlace/server/
there is a test function hello() in class Authentication it should return the string 'Hello World Åäö!'

regard,
Johan Axlesson

**Comment by nesium** [comment]
ok, so the problem was that SabreAMF sends the string as latin1. the unarchiver now falls back to latin1 if decoding the string as utf8 fails.

cheers,
marc

**Comment by johax** [comment]
thank you, works great now.

cheers,
johan
