### ISSUE TITLE
iPad

### ISSUE THREAD

**Issue by filharvey** [nesium/cocoa-amf#6]
I've converted my iPhone project which uses CocoaAMF very nicely from a Facebook Flash App, but tried to build an iPad version of it and got a compile error.

  ".objc_class_name_AMFUnarchiver", referenced from:
      literal-pointer@__OBJC@__cls_refs@AMFUnarchiver in EAGLView.o
  ".objc_class_name_AMFArchiver", referenced from:
      literal-pointer@__OBJC@__cls_refs@AMFArchiver in EAGLView.o
  ".objc_class_name_AMFRemotingCall", referenced from:
      literal-pointer@__OBJC@__cls_refs@AMFRemotingCall in EAGLView.o

Thanks

Any help would be great so I could get both versions out this month.

Phil

**Comment by nesium** [comment]
hi phil.

i suppose you haven't checked the *.m files for compilation in your target. but that's not related to cocoa-amf.

marc

**Comment by filharvey** [comment]
Nope all is checked in, and the same project as the working iPhone build. Just download the lastest SDK and target for iPad.

Phil
